### ISSUE TITLE
Audit Log: log user IP address  

### ISSUE THREAD

**Issue by Augustyn** [Augustyn/confluence-confidentiality#4]
Regarding line: [AuditLogger#L36](https://github.com/Augustyn/confluence-confidentiality/blob/9a911a0785b83c8e13b8adfd4f712f64984934c5/src/main/java/ch/nine/confluence/confidentiality/auditlog/AuditLogger.kt#L36): 
> .remoteAddress("127.0.0.1") //remote address cannot be null.

As in [comment](https://github.com/ninech/confluence-confidentiality/pull/2#discussion_r296792803):
 
> Maybe we could get the users IP address here? Something like: https://community.developer.atlassian.com/t/retrieve-user-ip-address-from-eventlistener-in-an-osgi-plugin/15359/5

**Comment by thde** [comment]
Should be fixed here: https://github.com/ninech/confluence-confidentiality/pull/3/files
